### ISSUE TITLE
GUI needs to (securely!) download + install a Tahoe release

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/tahoe-gui#4]
This will be platform-specific.

For Linux:

 - ask PyPI what the latest version of "tahoe-lafs" is
 - download the distribution and .sig from PyPI
 - check signature
 - make sure signature's public-key is the same as one in tahoe-gui's source
 - create virtualenv
 - "pip install" install package from PyPI into the virtualenv

For OS/X:

 - figure out latest version (how?)
 - download distribution + sig (from where?)
 - check sig
 - check sig's public key
 - install (how?)

For Windows:

 - figure out latest version (how?)
 - download distribution + sig (from where?)
 - check sig
 - check sig's public key
 - install (how?)

**Comment by meejah** [comment]
Hmm, okay maybe it *doesn't* as @crwood has cleverly embedded a Tahoe release into the OS X and Windows bundles of tahoe-gui. So: on OS/X and Windows, the "install" step is just "find the embedded tahoe binary".

That still leaves Linux. 

 - ideally, the user uses their distribution's packages
 - if not, it's probably best if *we* run "pip install" for them as the chance of checking signatures on the tahoe release is then way higher.

**Comment by crwood** [comment]
Yup! :)

re. Linux, is it still the case that `pip install tahoe-lafs` requires the prior installation of packages like python-dev, libssl-dev, and libffi-dev (and probably others) on Debian? If so, running `pip install tahoe-lafs` on the user's behalf would be insufficient here..

**Comment by meejah** [comment]
That's true (and yes, it will need a certain amount of packages).

For now, "exercise to the reader" is fine for Linux. (i.e. "install from your distro in 2 months when the packages hit testing :/) e.g. I see jessie currently has 1.10.0 (and tahoe-lafs is not in jessie-backports nor wheezy-backports at all). stretch has 1.11.0 at least.

(My thinking was that a managed venv would be easier / less-disruptive to mess around with if the GUI thought it was time to do updates, or if we wanted to install any extra packages, tools, etc). So, don't need TahoeEnvironment (which is probably a bad name anyway).
