### ISSUE TITLE
dmg link is bad

### ISSUE THREAD

**Issue by puppycodes** [LeastAuthority/tahoe-gui#6]
Link is broken to dmg - > https://buildbot.gridsync.io/packages/Tahoe-GUI.dmg

**Comment by crwood** [comment]
Hi there!

Development efforts in this repo have been merged/migrated to the [Gridsync project](https://github.com/gridsync/gridsync), which now does all the things Tahoe-GUI does (and where, I'm guessing, all future development will be happening moving forward..). Accordingly, this repo should _probably_ be removed.

In any case, fresh DMGs can be found there (under the [Releases](https://github.com/gridsync/gridsync/releases) tab) that _should_ be working -- please let me know over there if they don't! :)
