### ISSUE TITLE
Links to binaries for OS X and Windows are invalid

### ISSUE THREAD

**Issue by BrettDikeman** [LeastAuthority/tahoe-gui#7]
Greetings! The link to the binaries for OS X and Windows are invalid. Presently, they are:

https://buildbot.gridsync.io/packages/Tahoe-GUI.dmg
https://buildbot.gridsync.io/packages/Tahoe-GUI-win64.zip

...and both links return:

> **No Such Resource**
> File not found.

**Comment by crwood** [comment]
Hi there!

This project/repo has been superseded by the "[Gridsync](https://github.com/gridsync/gridsync)" one (which now does everything that "tahoe-gui" once did); you'll be able to find stable releases for Windows/Mac/Linux here: https://github.com/gridsync/gridsync
